USE [Funcionarios&Terceirizados]
GO

CREATE TABLE FUNCIONARIOS(
Nome             VARCHAR(40),
Horas_Expediente INTEGER,
valor_Por_Hora   NUMERIC)

INSERT INTO FUNCIONARIOS VALUES ('ALEX', '50', '20.00')

INSERT INTO FUNCIONARIOS VALUES ('MARIA', '60', '20.00')

SELECT * FROM FUNCIONARIOS

CREATE TABLE FUNCIONARIOS_TERCEIRIZADOS (
Nome              VARCHAR (40),
Horas_Expediente  INTEGER,
valor_Por_Hora    NUMERIC,
Adcional          NUMERIC)

INSERT INTO FUNCIONARIOS_TERCEIRIZADOS VALUES ('BOB', '100', '15.00', '200.00')

SELECT * FROM FUNCIONARIOS_TERCEIRIZADOS